import type { Dict } from "./types";

export const en: Dict = {
  meta: {
    title: "Empire Group — Mobile Apps, Websites, AI & Odoo ERP | Tashkent",
    description:
      "Mobile apps, websites, custom software and Odoo ERP + AI solutions for business. From idea to finished product in 2–3 months.",
  },
  nav: {
    links: [
      { label: "Services", href: "#xizmatlar" },
      { label: "Process", href: "#jarayon" },
      { label: "Projects", href: "#loyihalar" },
      { label: "Reviews", href: "#sharhlar" },
      { label: "Blog", href: "/blog" },
    ],
    cta: { label: "Free consultation", href: "#aloqa" },
    langLabel: "Language",
    themeLabel: "Theme",
  },
  hero: {
    eyebrow: "AI & Custom App Development for Businesses",
    title: "We build IT solutions that spare your business the headaches.",
    titleAccent: "spare your business the headaches",
    subtitle:
      "We digitize complex internal processes through ERP, AI, Web and App solutions. From idea to a finished system/product — in just 2–3 months.",
    primaryCta: { label: "Start a project", href: "#aloqa" },
    secondaryCta: { label: "See our work", href: "#loyihalar" },
    microline: "From idea to finished product — in 2–3 months",
    stats: [
      { value: "50+", label: "Projects delivered" },
      { value: "30+", label: "Happy clients" },
      { value: "15+", label: "Technologies" },
      { value: "3+ yrs", label: "Experience" },
    ],
    spec: {
      label: "// SERVICE SPEC",
      status: "ACCEPTING PROJECTS",
      rows: [
        { k: "TRACK", v: "Mobile / Advanced" },
        { k: "PRICE", v: "$35,000 – $50,000" },
        { k: "TIMELINE", v: "4 – 6 mo" },
        { k: "STACK", v: "Flutter · Firebase · API" },
      ],
    },
    flow: {
      problemLabel: "PROBLEM",
      solutionLabel: "SOLUTION",
      problemTitle: "Scattered, manual processes",
      problemItems: ["Excel spreadsheets", "Scattered chats", "Manual bookkeeping", "Lost orders"],
      solutionTitle: "Empire — one system",
      solutionItems: ["A single dashboard", "Automated", "Real-time control"],
      metricValue: "−70%",
      metricLabel: "manual work",
    },
  },
  showcase: {
    caption: "Real products built by Empire Group.",
    tabs: [
      { id: "crm", label: "CRM System", title: "Motor Lux CRM", subtitle: "Clients, sales and stages on one screen" },
      { id: "mobile", label: "Mobile App", title: "Delivery app", subtitle: "Orders, payment and notifications — in your pocket" },
      { id: "erp", label: "Odoo ERP", title: "Warehouse & ERP", subtitle: "Stock, supply and reports in one panel" },
      { id: "ecommerce", label: "E-commerce", title: "Online store", subtitle: "Catalog, cart and checkout — fast and reliable" },
    ],
  },
  consult: {
    title: "Free consultation",
    subtitle:
      "Leave your details — we'll get in touch and discuss your idea, budget and timeline together.",
    nameLabel: "Your name",
    namePlaceholder: "e.g. Murod",
    fieldLabel: "Direction",
    fieldPlaceholder: "Select a direction",
    fieldOptions: [
      "Mobile app",
      "Website",
      "Custom software",
      "Odoo ERP & AI",
    ],
    phoneLabel: "Phone",
    phonePlaceholder: "+998 90 123 45 67",
    emailLabel: "Email",
    emailPlaceholder: "you@email.com",
    budgetLabel: "Budget",
    budgetPlaceholder: "Select a budget",
    budgetOptions: [
      "$7,500 – $15,000",
      "$15,000 – $50,000",
      "$50,000+",
    ],
    messageLabel: "Message / about the project",
    messagePlaceholder: "Briefly describe your project…",
    submit: "Send request",
    sending: "Sending…",
    successTitle: "Thank you! Request received",
    successBody: "We'll get in touch soon and discuss your project.",
    errorRequired: "This field is required",
    errorPhone: "Enter a valid phone number",
    errorSubmit:
      "An error occurred while sending. Please try again or write to us on Telegram.",
    privacy: "Your data will not be shared with third parties.",
    close: "Close",
    responseBadge: "We'll reply shortly",
    urgency: "only a few project slots left this month",
    orLabel: "or",
    telegramCta: "Write on Telegram",
    telegramPrefill: "Hello! Empire Group — I'd like a consultation about a project.",
  },
  proof: {
    eyebrow: "Trusted by",
    title: "Trusted by",
    stats: [],
    clientsLabel: "Trusted by",
  },
  services: {
    eyebrow: "Services",
    title: "Four directions, one standard.",
    subtitle:
      "A clear package for every project — from a small MVP to a large corporate system. We'll decide where to start together.",
    popularLabel: "MOST POPULAR",
    ctaLabel: "Consultation",
    ctaHref: "#aloqa",
    priceFromLabel: "",
    items: [
      {
        no: "01",
        icon: "apps",
        title: "Mobile apps",
        body:
          "Cross-platform and native mobile apps. From a business MVP to high-load native apps/marketplaces — fully ready for the App Store and Google Play.",
        points: ["UI/UX design", "API integration", "Push notifications", "4 weeks of support"],
        stack: ["Flutter", "React Native", "Firebase", "iOS/Android"],
        accent: "preview",
        packages: [
          { name: "STANDARD", price: "from $5,000", term: "3–4 weeks", desc: "Prototype / MVP: cross-platform, core features, single platform." },
          { name: "ADVANCED", price: "$10K – $35K", term: "Negotiable", desc: "Complex business logic, API integrations, both platforms, custom design.", popular: true },
          { name: "MEGA", price: "$50,000+", term: "Negotiable", desc: "High-load marketplace / native app, multi-role system, architecture." },
        ],
      },
      {
        no: "02",
        icon: "systems",
        title: "Web applications",
        body:
          "Corporate platforms and web applications. From a landing page to high-load e-commerce and ERP portals — with a secure, fast and modern frontend architecture.",
        points: ["UI/UX design", "Reactive frontend", "Backend & API", "Admin panel", "SEO ready", "Hosting setup"],
        stack: ["React", "Next.js", "Laravel", "PostgreSQL", "Node.js"],
        accent: "develop",
        packages: [
          { name: "STANDARD", price: "from $5,000", term: "2–3 weeks", desc: "Corporate site / landing: UI/UX design, core pages, responsive design." },
          { name: "ADVANCED", price: "$20K – $40K", term: "Negotiable", desc: "Web application, optimized, admin panel, integrations.", popular: true },
          { name: "MEGA", price: "$50,000+", term: "Negotiable", desc: "E-commerce / ERP portal, high-load, microservice architecture." },
        ],
      },
      {
        no: "03",
        icon: "automation",
        title: "Custom software",
        body:
          "Custom-tailored systems for your business. When off-the-shelf solutions aren't enough — software built from scratch to fit your business processes.",
        points: ["Business analysis", "Architecture design", "Backend system", "Integrations", "Cloud deploy", "Technical documentation"],
        stack: ["Python", "Go", "PostgreSQL", "Docker", "Kubernetes"],
        accent: "ship",
        packages: [
          { name: "STANDARD", price: "$10,000", term: "4–6 weeks", desc: "Automation of a specific business process, module, integration." },
          { name: "ADVANCED", price: "$30K – $45K", term: "Negotiable", desc: "Multi-module system, business process automation, complex logic.", popular: true },
          { name: "MEGA", price: "$90,000+", term: "Negotiable", desc: "Large corporate platform, microservice architecture, high load." },
        ],
      },
      {
        no: "04",
        icon: "consulting",
        title: "Odoo ERP & AI Implementation",
        body:
          "All your operations in one solution. Full digitization of internal processes with the Odoo ecosystem and AI agents — sales, warehouse, accounting, HR, clients.",
        points: ["Business analysis", "Module setup", "Data migration", "Odoo integration", "AI agents", "Training/support"],
        stack: ["Odoo", "Python", "PostgreSQL", "AI Agents", "REST API"],
        accent: "develop",
        packages: [
          { name: "STANDARD", price: "$8,800", term: "3–4 weeks", desc: "Setup of standard Odoo modules, data migration, training." },
          { name: "ADVANCED", price: "$25K – $30K", term: "Negotiable", desc: "Full ERP implementation, integrations, AI agents, process automation.", popular: true },
          { name: "MEGA", price: "$85,000+", term: "Negotiable", desc: "Corporate ERP + AI transformation, predictive analytics, cloud architecture." },
        ],
      },
    ],
  },
  portfolio: {
    eyebrow: "Portfolio",
    title: "Our latest work.",
    subtitle: "Real, launched projects — each one a solved problem.",
    desktopLabel: "Desktop",
    mobileLabel: "Mobile",
    resultLabel: "Result",
    liveLabel: "Details",
    ctaTitle: "The next one is yours",
    ctaBody: "This spot is for your project. We'll turn the idea into a finished product together.",
    ctaButton: "Let's start your project",
    cases: [
      { segment: "Automotive · CRM", title: "Motor Lux — CRM and sales management", result: "Sales and clients in one system", tags: ["CRM", "Web"], desktopImg: "/cases/case-autoservice-desktop.webp", mobileImg: "/cases/case-autoservice-mobile.webp", url: "motorlux.uz", accent: "develop" },
      { segment: "Healthcare · CRM (PWA)", title: "MedFlow — clinic CRM and patient intake", result: "Intake management 3× faster", tags: ["PWA", "CRM"], desktopImg: "/cases/case-medflow-desktop.webp", mobileImg: "/cases/case-medflow-mobile.webp", url: "medflow.uz", accent: "preview" },
      { segment: "Textile · ERP (PWA)", title: "Grand Osiyo Textile — ERP and warehouse system", result: "Warehouse managed in real time", tags: ["ERP", "Warehouse"], desktopImg: "/cases/case-textile-desktop.webp", mobileImg: "/cases/case-textile-mobile.webp", url: "grandosiyo.uz", accent: "ship" },
      { segment: "Rental · Catalog", title: "Texnika Ijara — rental and catalog site", result: "Online bookings up 3×", tags: ["Web", "Catalog"], desktopImg: "/cases/case-texnika-desktop.webp", mobileImg: "/cases/case-texnika-mobile.webp", url: "texnika-ijara.uz", accent: "develop" },
      { segment: "Electronics · E-commerce", title: "GadgetSpace — online electronics store", result: "Conversion up 2.1×", tags: ["E-commerce"], desktopImg: "/cases/case-gadgetspace-desktop.webp", mobileImg: "/cases/case-gadgetspace-mobile.webp", url: "gadgetspace.uz", accent: "ship" },
      { segment: "Fashion brand · E-commerce", title: "X Wear — store for a clothing brand", result: "Average order value up 28%", tags: ["E-commerce", "Web"], desktopImg: "/cases/case-xwear-desktop.webp", mobileImg: "/cases/case-xwear-mobile.webp", url: "xwear.uz", accent: "preview" },
      { segment: "Retail · POS", title: "Hilol Market — retail automation", result: "Checkout 2× faster", tags: ["Retail", "POS"], desktopImg: "/cases/case-kassa-desktop.webp", mobileImg: "/cases/case-kassa-mobile.webp", url: "hilolmarket.uz", accent: "develop" },
    ],
  },
  features: {
    eyebrow: "Deeper",
    resultLabel: "Result",
    blocks: [
      { kicker: "Odoo ERP & AI", title: "All operations — in one system", body: "Sales, warehouse, accounting and HR were scattered across separate spreadsheets. We deployed Odoo ERP and AI agents — processes now live in one panel and run automatically.", result: "Internal processes fully digitized", frame: "browser", accent: "develop" },
      { kicker: "Mobile app", title: "A business in the client's pocket is a strong business", body: "We built a mobile app for the segment — orders, payment, notifications all in one place. Now the client carries your business in their pocket every day.", result: "Repeat orders up 2×", frame: "phone", accent: "preview" },
      { kicker: "Custom software", title: "Manual work — a hidden cost", body: "Admins spent hours a day repeating the same task. We handed it to a custom system and integrations. Now the system runs 24/7 and doesn't make mistakes.", result: "Manual labor cut by 70%", frame: "browser", accent: "ship" },
    ],
  },
  founder: {
    eyebrow: "Contact",
    title: "Empire Group",
    name: "Empire Group",
    role: "AI & Custom App Development · Tashkent",
    bio: [
      "We shorten the path from idea to finished product — with ERP, AI, Web and App solutions.",
      "In every project, one thing matters — the result: a working system that moves the business forward.",
    ],
    photo: "/founder.webp",
    quote: "We don't write code — we solve your business's problem.",
    socials: [
      { label: "Telegram", value: "@muslimansoriy", href: "https://t.me/muslimansoriy" },
      { label: "Phone", value: "+998 99 116 46 58", href: "tel:+998991164658" },
      { label: "Email", value: "muslimansoriy7@gmail.com", href: "mailto:muslimansoriy7@gmail.com" },
    ],
  },
  process: {
    eyebrow: "How we work",
    title: "Explore → Plan → Build → Commit",
    ctaLabel: "Start a project",
    ctaHref: "#aloqa",
    steps: [
      { no: "01", title: "Explore", body: "We understand the idea and the problem. We study your business, goals and pain points in depth. Together we define the direction of the solution.", tags: ["Analysis", "Audit"] },
      { no: "02", title: "Plan", body: "Planning and writing the PRD. Technical spec, architecture, design — everything is documented. Timeline and budget become precise.", tags: ["PRD", "Spec", "Design"] },
      { no: "03", title: "Build", body: "We develop — code, tests and integration. We work in sprints and show a demo at every stage. You watch the process in real time.", tags: ["Dev", "Test", "Demo"] },
      { no: "04", title: "Commit", body: "Launch and long-term support. We launch, train your team and provide long-term technical support.", tags: ["Deploy", "Support"] },
    ],
  },
  whyUs: {
    eyebrow: "Why Empire Group",
    title: "A reliable partner — from start to finish.",
    items: [
      { title: "Fixed-scope pricing", body: "An agreed price — no hidden costs. You know exactly what you're paying for." },
      { title: "Senior engineers", body: "An experienced team: with a track record of systems shipped to production." },
      { title: "Transparent timeline", body: "Every sprint's result is visible; you follow the process in real time." },
      { title: "Full ownership", body: "Code, design and data — all yours. No vendor lock-in whatsoever." },
      { title: "Post-launch support", body: "Support and further development even after launch." },
      { title: "Modern stack", body: "Flutter, React, Next.js, Odoo, AI — modern and stable technologies." },
    ],
  },
  testimonials: {
    eyebrow: "Client feedback",
    title: "What our clients say.",
    items: [
      { quote: "Empire Group moved our old paper-based work entirely into a system. Now we manage all orders from one place — it saved a lot of time.", name: "Aliya M.", role: "CRM project · Motor Lux" },
      { quote: "Working with Empire was easy. The timeline and budget were clear, and no surprises came up.", name: "Jasur T.", role: "E-commerce · GadgetSpace" },
      { quote: "Empire automated the clinic's work by adding AI. The patient queue problem was solved and intake is much more orderly.", name: "Doniyor R.", role: "MedFlow · clinic" },
      { quote: "A modern design and a fast site. Sales volume went up and client feedback is positive.", name: "Laziza K.", role: "X Wear · e-commerce" },
    ],
    proofTitle: "Live proof from Telegram",
    proofNote: "Real conversations with clients",
  },
  brands: {
    eyebrow: "Global standard",
    title: "We work to a world-class standard.",
    subtitle:
      "The technologies, platforms and standards the biggest companies trust — now in your project too.",
  },
  stack: {
    eyebrow: "Our stack",
    title: "Reliable, industry-standard technologies.",
    subtitle:
      "Every project runs on modern, stable tools proven across millions of users.",
  },
  faq: {
    eyebrow: "Q&A",
    title: "Frequently asked questions.",
    items: [
      { q: "How long does a project take?", a: "A small MVP takes 3–4 weeks, a medium project 2–3 months, a large corporate system 4–6 months. The exact timeline is set during the Explore phase." },
      { q: "How is the price calculated?", a: "Fixed-scope: once the project scope is defined, an exact price is given. No hidden costs. Packages start from $5,000." },
      { q: "Why do prices differ?", a: "Price depends on complexity, integrations and timeline. We calculate it separately for each project." },
      { q: "Do you provide support after development?", a: "Yes — after launch, support, bug fixes and further development continue." },
      { q: "How is payment made?", a: "In stages: a portion upfront, then based on sprint results. Payment methods are agreed upon." },
      { q: "Who owns the code and data?", a: "It all belongs to you. Full ownership is yours — no vendor lock-in." },
      { q: "Can you continue my existing system?", a: "Yes — we'll review the existing project or system and offer a solution to continue or rebuild it." },
      { q: "Is the consultation free?", a: "Yes. During the Explore phase we answer all questions and draw up a clear plan — with no obligation." },
    ],
  },
  cta: {
    eyebrow: "Free consultation",
    title: "Get a free consultation — then decide.",
    subtitle: "Fill out the form and we'll get in touch. Together we'll discuss the idea, budget and timeline. No obligation — a conversation first.",
    button: { label: "Free consultation", href: "https://t.me/muslimansoriy" },
    formTitle: "Free consultation",
    formSubtitle: "Leave your details — we'll be in touch shortly.",
  },
  footer: {
    tagline: "AI & Custom App Development. IT solutions for your business.",
    columns: [
      { title: "Services", links: [
        { label: "Mobile app", href: "#xizmatlar" },
        { label: "Website", href: "#xizmatlar" },
        { label: "Custom software", href: "#xizmatlar" },
        { label: "Odoo ERP & AI", href: "#xizmatlar" },
      ]},
      { title: "Company", links: [
        { label: "Projects", href: "#loyihalar" },
        { label: "Process", href: "#jarayon" },
        { label: "Reviews", href: "#sharhlar" },
        { label: "Blog", href: "/blog" },
      ]},
      { title: "Contact", links: [
        { label: "Telegram (@muslimansoriy)", href: "https://t.me/muslimansoriy" },
        { label: "+998 99 116 46 58", href: "tel:+998991164658" },
        { label: "muslimansoriy7@gmail.com", href: "mailto:muslimansoriy7@gmail.com" },
      ]},
    ],
    copyright: "© 2026 Empire Group. All rights reserved.",
  },
};
