import type { Dict } from "./types";

export const en: Dict = {
  meta: {
    title: "Empire Group — Mobile Apps, Websites, AI & Odoo ERP | Tashkent",
    description:
      "Mobile apps, websites, custom software and Odoo ERP + AI solutions for business. From idea to finished product in 2–3 months.",
  },
  nav: {
    links: [
      { label: "Services", href: "#xizmatlar" },
      { label: "Process", href: "#jarayon" },
      { label: "Projects", href: "#loyihalar" },
      { label: "Reviews", href: "#sharhlar" },
      { label: "Blog", href: "/blog" },
    ],
    cta: { label: "Free consultation", href: "#aloqa" },
    phone: { label: "+998 99 116 46 58", href: "tel:+998991164658" },
    langLabel: "Language",
    themeLabel: "Theme",
  },
  hero: {
    eyebrow: "AI & Custom App Development for Businesses",
    title: "We build IT solutions that save your business {word}.",
    titleAccent: "{word}",
    rotatingWords: ["time", "nerves", "money"],
    subtitle:
      "We digitize complex internal processes through ERP, AI, Web and App solutions. From idea to a finished system/product — in just 2–3 months.",
    primaryCta: { label: "Start a project", href: "#aloqa" },
    secondaryCta: { label: "See our work", href: "#loyihalar" },
    microline: "From idea to finished product — in 2–3 months",
    stats: [
      { value: "50+", label: "Projects delivered" },
      { value: "30+", label: "Happy clients" },
      { value: "15+", label: "Technologies" },
      { value: "3+ yrs", label: "Experience" },
    ],
    spec: {
      label: "// SERVICE SPEC",
      status: "ACCEPTING PROJECTS",
      rows: [
        { k: "TRACK", v: "Mobile / Advanced" },
        { k: "PRICE", v: "$35,000 – $50,000" },
        { k: "TIMELINE", v: "4 – 6 mo" },
        { k: "STACK", v: "Flutter · Firebase · API" },
      ],
    },
    flow: {
      problemLabel: "PROBLEM",
      solutionLabel: "SOLUTION",
      problemTitle: "Siloed departments, manual books",
      problemItems: [
        "Stock levels unclear",
        "Departments siloed",
        "Reports arrive late",
        "Manual Excel books",
      ],
      solutionTitle: "Empire — one ERP system",
      solutionItems: [
        "One database, one panel",
        "Processes automated",
        "Real-time reporting",
      ],
      metricValue: "−70%",
      metricLabel: "manual work",
    },

  },
  showcase: {
    caption: "Real products built by Empire Group.",
    tabs: [
      { id: "crm", label: "CRM System", title: "Motor Lux CRM", subtitle: "Clients, sales and stages on one screen" },
      { id: "mobile", label: "Mobile App", title: "Delivery app", subtitle: "Orders, payment and notifications — in your pocket" },
      { id: "erp", label: "Odoo ERP", title: "Warehouse & ERP", subtitle: "Stock, supply and reports in one panel" },
      { id: "ecommerce", label: "E-commerce", title: "Online store", subtitle: "Catalog, cart and checkout — fast and reliable" },
    ],
  },
  consult: {
    title: "Free consultation",
    subtitle:
      "Leave your details — we'll get in touch and discuss your idea, budget and timeline together.",
    nameLabel: "Your name",
    namePlaceholder: "e.g. Murod",
    fieldLabel: "Direction",
    fieldPlaceholder: "Select a direction",
    fieldOptions: [
      "Custom software",
      "Odoo ERP & AI implementation",
    ],
    phoneLabel: "Phone",
    phonePlaceholder: "+998 90 123 45 67",
    emailLabel: "Email",
    emailPlaceholder: "you@email.com",
    budgetLabel: "Budget",
    budgetPlaceholder: "Select a budget",
    budgetOptions: [
      "$5,000 – $15,000",
      "$15,000 – $50,000",
      "$50,000+",
      "Not decided yet",
    ],
    messageLabel: "Message / about the project",
    messagePlaceholder: "Briefly describe your project…",
    submit: "Send request",
    sending: "Sending…",
    successTitle: "Thank you! Request received",
    successBody: "We'll get in touch soon and discuss your project.",
    errorRequired: "This field is required",
    errorPhone: "Enter a valid phone number",
    errorSubmit:
      "An error occurred while sending. Please try again or write to us on Telegram.",
    privacy: "Your data will not be shared with third parties.",
    close: "Close",
    responseBadge: "We'll reply shortly",
    urgency: "only a few project slots left this month",
    orLabel: "or",
    telegramCta: "Write on Telegram",
    telegramPrefill: "Hello! Empire Group — I'd like a consultation about a project.",
  },
  proof: {
    eyebrow: "Trusted by",
    title: "Trusted by",
    stats: [],
    clientsLabel: "Trusted by",
  },
  services: {
    eyebrow: "Services",
    title: "Two disciplines, one standard.",
    subtitle:
      "Three packages per project — from a fast MVP to a large corporate system. Pricing is fixed-scope: agreed at the start of the project.",
    popularLabel: "MOST CHOSEN",
    ctaLabel: "Consultation",
    ctaHref: "#aloqa",
    priceFromLabel: "",
    inclLabel: "What the package includes",
    items: [
      {
        no: "01",
        icon: "automation",
        tag: "Custom Software Development",
        title: "Custom software",
        subtitle: "Solutions shaped around your internal business processes",
        geoSlug: "crm-erp-toshkent",
        detailsLabel: "More about {name} →",
        body:
          "We build custom web apps, mobile apps and internal systems around the operational needs of a real, running business — not a template bent to fit, but a precise answer to your own process.",
        points: [
          "Business analysis and process map",
          "UI/UX design",
          "Web or mobile app (iOS + Android)",
          "Backend, API and admin panel",
          "Integrations (Telegram, CRM, payments)",
          "4 weeks of support",
        ],
        stack: ["React", "Node.js", "Flutter", "Swift", "Kotlin", "Laravel", "Docker", "AWS"],
        accent: "ship",
        packages: [
          {
            name: "STANDARD",
            price: "from $5,000",
            term: "2 – 3 months",
            desc: "An MVP that solves one clear job: landing + form, a small mobile app or an internal web panel. For getting to market fast.",
          },
          {
            name: "ADVANCED",
            price: "$15K – $40K",
            term: "4 – 6 months",
            desc: "A full web or mobile app with complex business logic — CRM integration, push notifications, admin panel and API.",
            popular: true,
          },
          {
            name: "MEGA",
            price: "$50,000+",
            term: "6 – 12 months",
            desc: "Large ecosystems: several apps (web + mobile + admin), microservice architecture, high load and cloud infrastructure.",
          },
        ],
      },
      {
        no: "02",
        icon: "consulting",
        tag: "Odoo ERP & AI Implementation",
        title: "Odoo ERP & AI implementation",
        subtitle: "Bringing scattered processes into one system and sharpening it with AI",
        geoSlug: "crm-erp-toshkent",
        detailsLabel: "More about {name} →",
        body:
          "We merge the separately running departments, spreadsheets and manual steps of a company into a single centralised digital system. On top of it we add AI automation and take the repetitive mechanical work off your team entirely.",
        points: [
          "Business process analysis and map",
          "Odoo module configuration or custom ERP",
          "Data migration",
          "AI / chatbot integration",
          "Staff training",
          "Support and monitoring",
        ],
        stack: ["Odoo ERP", "AI Automation", "Predictive Analytics", "Cloud"],
        accent: "develop",
        packages: [
          {
            name: "STANDARD",
            price: "from $8,800",
            term: "2 – 3 months",
            desc: "Baseline configuration of standard Odoo modules, data migration and staff training. A first step for small and mid-size businesses.",
          },
          {
            name: "ADVANCED",
            price: "$25K – $35K",
            term: "4 – 6 months",
            desc: "Odoo modules tailored to your requirements, smart chatbots, document flow and process automation.",
            popular: true,
          },
          {
            name: "MEGA",
            price: "$85,000+",
            term: "1 year",
            desc: "Full digital transformation for a large company: Odoo ERP across every department, predictive analytics and deep AI integration.",
          },
        ],
      },
    ],
  },
  portfolio: {
    eyebrow: "Portfolio",
    title: "Our latest work.",
    subtitle: "Real, launched projects — each one a solved problem.",
    desktopLabel: "Desktop",
    mobileLabel: "Mobile",
    resultLabel: "Result",
    liveLabel: "Details",
    ctaTitle: "The next one is yours",
    ctaBody: "This spot is for your project. We'll turn the idea into a finished product together.",
    ctaButton: "Let's start your project",
    cases: [
      { segment: "Automotive · CRM", title: "Motor Lux — CRM and sales management", result: "Sales and clients in one system", tags: ["CRM", "Web"], desktopImg: "/cases/case-autoservice-desktop.webp", mobileImg: "/cases/case-autoservice-mobile.webp", url: "motorlux.uz", accent: "develop" },
      { segment: "Healthcare · CRM (PWA)", title: "MedFlow — clinic CRM and patient intake", result: "Intake management 3× faster", tags: ["PWA", "CRM"], desktopImg: "/cases/case-medflow-desktop.webp", mobileImg: "/cases/case-medflow-mobile.webp", url: "medflow.uz", accent: "preview" },
      { segment: "Textile · ERP (PWA)", title: "Grand Osiyo Textile — ERP and warehouse system", result: "Warehouse managed in real time", tags: ["ERP", "Warehouse"], desktopImg: "/cases/case-textile-desktop.webp", mobileImg: "/cases/case-textile-mobile.webp", url: "grandosiyo.uz", accent: "ship" },
      { segment: "Rental · Catalog", title: "Texnika Ijara — rental and catalog site", result: "Online bookings up 3×", tags: ["Web", "Catalog"], desktopImg: "/cases/case-texnika-desktop.webp", mobileImg: "/cases/case-texnika-mobile.webp", url: "texnika-ijara.uz", accent: "develop" },
      { segment: "Electronics · E-commerce", title: "GadgetSpace — online electronics store", result: "Conversion up 2.1×", tags: ["E-commerce"], desktopImg: "/cases/case-gadgetspace-desktop.webp", mobileImg: "/cases/case-gadgetspace-mobile.webp", url: "gadgetspace.uz", accent: "ship" },
      { segment: "Fashion brand · E-commerce", title: "X Wear — store for a clothing brand", result: "Average order value up 28%", tags: ["E-commerce", "Web"], desktopImg: "/cases/case-xwear-desktop.webp", mobileImg: "/cases/case-xwear-mobile.webp", url: "xwear.uz", accent: "preview" },
      { segment: "Retail · POS", title: "Hilol Market — retail automation", result: "Checkout 2× faster", tags: ["Retail", "POS"], desktopImg: "/cases/case-kassa-desktop.webp", mobileImg: "/cases/case-kassa-mobile.webp", url: "hilolmarket.uz", accent: "develop" },
    ],
  },
  features: {
    eyebrow: "Deeper",
    resultLabel: "Result",
    blocks: [
      { kicker: "Odoo ERP & AI", title: "All operations — in one system", body: "Sales, warehouse, accounting and HR were scattered across separate spreadsheets. We deployed Odoo ERP and AI agents — processes now live in one panel and run automatically.", result: "Internal processes fully digitized", frame: "browser", accent: "develop" },
      { kicker: "Mobile app", title: "A business in the client's pocket is a strong business", body: "We built a mobile app for the segment — orders, payment, notifications all in one place. Now the client carries your business in their pocket every day.", result: "Repeat orders up 2×", frame: "phone", accent: "preview" },
      { kicker: "Custom software", title: "Manual work — a hidden cost", body: "Admins spent hours a day repeating the same task. We handed it to a custom system and integrations. Now the system runs 24/7 and doesn't make mistakes.", result: "Manual labor cut by 70%", frame: "browser", accent: "ship" },
    ],
  },
  founder: {
    eyebrow: "Contact",
    title: "Empire Group",
    name: "Empire Group",
    role: "AI & Custom App Development · Tashkent",
    bio: [
      "We shorten the path from idea to finished product — with ERP, AI, Web and App solutions.",
      "In every project, one thing matters — the result: a working system that moves the business forward.",
    ],
    photo: "/founder.webp",
    quote: "We don't write code — we solve your business's problem.",
    socials: [
      { label: "Telegram", value: "@muslimansoriy", href: "https://t.me/muslimansoriy" },
      { label: "Phone", value: "+998 99 116 46 58", href: "tel:+998991164658" },
      { label: "Email", value: "muslimansoriy7@gmail.com", href: "mailto:muslimansoriy7@gmail.com" },
    ],
  },
  process: {
    eyebrow: "How we work",
    title: "Explore → Plan → Build → Commit",
    ctaLabel: "Start a project",
    ctaHref: "#aloqa",
    steps: [
      { no: "01", title: "Explore", body: "We understand the idea and the problem. We study your business, goals and pain points in depth. Together we define the direction of the solution.", tags: ["Analysis", "Audit"] },
      { no: "02", title: "Plan", body: "Planning and writing the PRD. Technical spec, architecture, design — everything is documented. Timeline and budget become precise.", tags: ["PRD", "Spec", "Design"] },
      { no: "03", title: "Build", body: "We develop — code, tests and integration. We work in sprints and show a demo at every stage. You watch the process in real time.", tags: ["Dev", "Test", "Demo"] },
      { no: "04", title: "Commit", body: "Launch and long-term support. We launch, train your team and provide long-term technical support.", tags: ["Deploy", "Support"] },
    ],
  },
  whyUs: {
    eyebrow: "Why Empire Group",
    title: "A reliable partner — from start to finish.",
    items: [
      { title: "Fixed-scope pricing", body: "An agreed price — no hidden costs. You know exactly what you're paying for." },
      { title: "Senior engineers", body: "An experienced team: with a track record of systems shipped to production." },
      { title: "Transparent timeline", body: "Every sprint's result is visible; you follow the process in real time." },
      { title: "Full ownership", body: "Code, design and data — all yours. No vendor lock-in whatsoever." },
      { title: "Post-launch support", body: "Support and further development even after launch." },
      { title: "Modern stack", body: "Flutter, React, Next.js, Odoo, AI — modern and stable technologies." },
    ],
  },
  testimonials: {
    eyebrow: "Client feedback",
    title: "What our clients say.",
    items: [
      { quote: "Empire Group moved our old paper-based work entirely into a system. Now we manage all orders from one place — it saved a lot of time.", name: "Aliya M.", role: "CRM project · Motor Lux" },
      { quote: "Working with Empire was easy. The timeline and budget were clear, and no surprises came up.", name: "Jasur T.", role: "E-commerce · GadgetSpace" },
      { quote: "Empire automated the clinic's work by adding AI. The patient queue problem was solved and intake is much more orderly.", name: "Doniyor R.", role: "MedFlow · clinic" },
      { quote: "A modern design and a fast site. Sales volume went up and client feedback is positive.", name: "Laziza K.", role: "X Wear · e-commerce" },
    ],
    proofTitle: "Live proof from Telegram",
    proofNote: "Real conversations with clients",
  },
  credentials: {
    eyebrow: "Standing and proof",
    title: "Official status and certificates.",
    subtitle:
      "Every partnership and status here is backed by an official document. The list grows as new certificates are issued.",
    activeLabel: "Confirmed",
    pendingLabel: "In progress",
    placeholderTitle: "Certificate",
    placeholderNote: "Reserved for the next certificate in progress.",
    viewLabel: "Click to view",
    closeLabel: "Close",
    prevLabel: "Previous",
    nextLabel: "Next",
    items: [
      {
        name: "Odoo Learning Partner",
        image: "/sertifikat/odoo-learning-partner.svg",
        issuer: "Odoo S.A.",
        note: "Official partnership status with Odoo. It grants direct access to product updates, the implementation methodology and vendor support.",
        status: "active",
      },
      {
        name: "Certificate of state registration",
        image: "/sertifikat/davlat-royxat-guvohnomasi.png",
        issuer: "Officially registered",
        note: "\"EMPIRE GROUP CORP\" LLC is a registered legal entity. The right to sign contracts, issue invoices and meet tax obligations is confirmed by the document.",
        status: "active",
      },
      {
        name: "IT Park resident",
        image: "/sertifikat/it-park.svg",
        imageBleed: true,
        issuer: "IT Park Uzbekistan",
        note: "An application has been filed to join the register of Uzbekistan's IT industry residents. Residency brings technology-park oversight, tax relief and access to state support programmes.",
        status: "pending",
      },
      {
        name: "ISO/IEC 27001",
        image: "/sertifikat/iso-27001.svg",
        issuer: "Information security standard",
        note: "The international standard for information security management. It sets out how a client database, finances and intellectual property are protected against cyberattacks and theft. Certification is pending.",
        status: "pending",
      },
    ],
  },
  faq: {
    eyebrow: "Q&A",
    title: "Frequently asked questions.",
    items: [
      { q: "How long does a project take?", a: "A small MVP takes 3–4 weeks, a medium project 2–3 months, a large corporate system 4–6 months. The exact timeline is set during the Explore phase." },
      { q: "How is the price calculated?", a: "Fixed-scope: once the project scope is defined, an exact price is given. No hidden costs. Packages start from $5,000." },
      { q: "Why do prices differ?", a: "Price depends on complexity, integrations and timeline. We calculate it separately for each project." },
      { q: "Do you provide support after development?", a: "Yes — after launch, support, bug fixes and further development continue." },
      { q: "How is payment made?", a: "In stages: a portion upfront, then based on sprint results. Payment methods are agreed upon." },
      { q: "Who owns the code and data?", a: "It all belongs to you. Full ownership is yours — no vendor lock-in." },
      { q: "Can you continue my existing system?", a: "Yes — we'll review the existing project or system and offer a solution to continue or rebuild it." },
      { q: "Is the consultation free?", a: "Yes. During the Explore phase we answer all questions and draw up a clear plan — with no obligation." },
    ],
  },
  cta: {
    eyebrow: "Free consultation",
    title: "Get a free consultation — then decide.",
    subtitle: "Fill out the form and we'll get in touch. Together we'll discuss the idea, budget and timeline. No obligation — a conversation first.",
    button: { label: "Free consultation", href: "https://t.me/muslimansoriy" },
    formTitle: "Free consultation",
    formSubtitle: "Leave your details — we'll be in touch shortly.",
  },
  blogCta: {
    title: "Have a project along these lines?",
    body: "We will work through how what the article describes applies to your business. The conversation is free and commits you to nothing.",
    cta: "Free consultation",
  },
  blogIndex: {
    allLabel: "All",
    emptyFiltered: "No articles in this area yet.",
  },
  footer: {
    tagline:
      "AI and custom app development for business — mobile, web, custom software and Odoo ERP & AI implementation. From idea to launch.",
    columns: [
      { title: "Services", links: [
        { label: "Custom software", href: "#xizmatlar" },
        { label: "Odoo ERP & AI implementation", href: "#xizmatlar" },
      ]},
      { title: "Company", links: [
        { label: "Projects", href: "#loyihalar" },
        { label: "Process", href: "#jarayon" },
        { label: "Client reviews", href: "#sharhlar" },
        { label: "FAQ", href: "#savollar" },
        { label: "Blog", href: "/blog" },
      ]},
      { title: "Contact", links: [
        { label: "muslimansoriy7@gmail.com", href: "mailto:muslimansoriy7@gmail.com" },
        { label: "+998 99 116 46 58", href: "tel:+998991164658" },
        { label: "Telegram", href: "https://t.me/muslimansoriy" },
        { label: "Instagram", href: "https://instagram.com/empiregroup.uz" },
      ]},
    ],
    copyright: "© 2026 Empire Group. All rights reserved.",
    legal: "Privacy policy · Terms of use",
  },
};
