import type { Dict } from "./types";

export const uz: Dict = {
  meta: {
    title: "Empire Group — Mobil ilova, Veb-sayt, AI va Odoo ERP | Toshkent",
    description:
      "Biznes uchun mobil ilova, veb-sayt, maxsus dasturiy ta'minot va Odoo ERP + AI yechimlari. G'oyadan tayyor mahsulotgacha 2–3 oyda.",
  },
  nav: {
    links: [
      { label: "Xizmatlar", href: "#xizmatlar" },
      { label: "Jarayon", href: "#jarayon" },
      { label: "Loyihalar", href: "#loyihalar" },
      { label: "Sharhlar", href: "#sharhlar" },
      { label: "Blog", href: "/blog" },
    ],
    cta: { label: "Bepul konsultatsiya", href: "#aloqa" },
    langLabel: "Til",
    themeLabel: "Mavzu",
  },
  hero: {
    eyebrow: "AI & Custom App Development for Businesses",
    title: "Biznes uchun {word} tejaydigan IT-yechimlar joriy qilamiz.",
    titleAccent: "{word}",
    rotatingWords: ["vaqt", "asab", "pul"],
    subtitle:
      "Murakkab ichki jarayonlarni ERP, AI, Web va App yechimlari orqali raqamlashtiramiz. G'oyadan tayyor tizim/mahsulotgacha — atigi 2–3 oyda.",
    primaryCta: { label: "Loyihani boshlash", href: "#aloqa" },
    secondaryCta: { label: "Ishlarni ko'rish", href: "#loyihalar" },
    microline: "G'oyadan tayyor mahsulotgacha — 2–3 oyda",
    stats: [
      { value: "50+", label: "Yakunlangan loyiha" },
      { value: "30+", label: "Mamnun mijoz" },
      { value: "15+", label: "Texnologiya" },
      { value: "3+ yil", label: "Tajriba" },
    ],
    spec: {
      label: "// XIZMAT SPEKI",
      status: "QABUL QILINMOQDA",
      rows: [
        { k: "YO'NALISH", v: "Mobile / Advanced" },
        { k: "BAHOSI", v: "$35,000 – $50,000" },
        { k: "MUDDAT", v: "4 – 6 oy" },
        { k: "STACK", v: "Flutter · Firebase · API" },
      ],
    },
    flow: {
      problemLabel: "MUAMMO",
      solutionLabel: "YECHIM",
      problemTitle: "Tarqoq bo'limlar, qo'lda hisob",
      problemItems: [
        "Ombor qoldig'i noaniq",
        "Bo'limlar uzilgan",
        "Hisobot kech keladi",
        "Qo'lda Excel hisobi",
      ],
      solutionTitle: "Empire — yagona ERP tizimi",
      solutionItems: [
        "Yagona baza, bitta panel",
        "Jarayonlar avtomatlashgan",
        "Real vaqtda hisobot",
      ],
      metricValue: "−70%",
      metricLabel: "qo'l mehnati",
    },

  },
  showcase: {
    caption: "Empire Group tomonidan qurilgan real mahsulotlar.",
    tabs: [
      { id: "crm", label: "CRM Tizimi", title: "Motor Lux CRM", subtitle: "Mijoz, savdo va bosqichlar bir ekranda" },
      { id: "mobile", label: "Mobil Ilova", title: "Yetkazib berish ilovasi", subtitle: "Buyurtma, to'lov va bildirishnoma — cho'ntakda" },
      { id: "erp", label: "Odoo ERP", title: "Ombor & ERP", subtitle: "Zaxira, ta'minot va hisobot bitta panelda" },
      { id: "ecommerce", label: "E-commerce", title: "Onlayn do'kon", subtitle: "Katalog, savat va to'lov — tez va ishonchli" },
    ],
  },
  consult: {
    title: "Bepul konsultatsiya",
    subtitle:
      "Ma'lumotlaringizni qoldiring — biz siz bilan bog'lanamiz va g'oyani, byudjetni va muddatni birga muhokama qilamiz.",
    nameLabel: "Ismingiz",
    namePlaceholder: "Masalan: Muslim",
    fieldLabel: "Yo'nalish",
    fieldPlaceholder: "Yo'nalishni tanlang",
    fieldOptions: [
      "Maxsus dasturiy ta'minot",
      "Odoo ERP & AI Joriy qilish",
    ],
    phoneLabel: "Telefon",
    phonePlaceholder: "+998 90 123 45 67",
    emailLabel: "Email",
    emailPlaceholder: "siz@email.com",
    budgetLabel: "Byudjet",
    budgetPlaceholder: "Byudjetni tanlang",
    budgetOptions: [
      "$7,500 – $15,000",
      "$15,000 – $50,000",
      "$50,000+",
    ],
    messageLabel: "Xabar / loyiha haqida",
    messagePlaceholder: "Loyihangiz haqida qisqacha yozing…",
    submit: "Ariza yuborish",
    sending: "Yuborilmoqda…",
    successTitle: "Rahmat! Qabul qilindi",
    successBody: "Tez orada siz bilan bog'lanamiz va loyihangizni muhokama qilamiz.",
    errorRequired: "Bu maydon to'ldirilishi shart",
    errorPhone: "To'g'ri telefon raqam kiriting",
    errorSubmit:
      "Yuborishda xatolik yuz berdi. Iltimos, qayta urinib ko'ring yoki Telegram orqali yozing.",
    privacy: "Ma'lumotlaringiz uchinchi shaxslarga berilmaydi.",
    close: "Yopish",
    responseBadge: "Tez orada javob beramiz",
    urgency: "bu oy atigi bir nechta loyiha uchun joy bor",
    orLabel: "yoki",
    telegramCta: "Telegram orqali yozish",
    telegramPrefill: "Assalomu alaykum! Empire Group — loyiha bo'yicha maslahatlashmoqchi edim.",
  },
  proof: {
    eyebrow: "Bizga ishonishadi",
    title: "Bizga ishonishadi",
    stats: [],
    clientsLabel: "Bizga ishonishadi",
  },
  services: {
    eyebrow: "Xizmatlar",
    title: "Ikki yo'nalish, bitta standart.",
    subtitle:
      "Har bir loyiha uchun uchta paket — tezkor MVP'dan tortib yirik korporativ tizimgacha. Narxlar fixed-scope: loyiha boshida aniq belgilanadi.",
    popularLabel: "KO'P TANLANADI",
    ctaLabel: "Konsultatsiya",
    ctaHref: "#aloqa",
    priceFromLabel: "",
    inclLabel: "Paketga kiradi",
    items: [
      {
        no: "01",
        icon: "automation",
        tag: "Custom Software Development",
        title: "Maxsus dasturiy ta'minot",
        subtitle: "Biznesingiz ichki jarayonlariga moslashtirilgan yechimlar",
        geoSlug: "crm-erp-toshkent",
        detailsLabel: "{name} haqida batafsil →",
        body:
          "Real ishlayotgan biznesning operatsion ehtiyojlaridan kelib chiqqan holda maxsus veb-ilovalar, mobil ilovalar va ichki tizimlar ishlab chiqamiz — tayyor shablonlarga moslash emas, biznesingizning o'ziga xos jarayoniga aniq yechim.",
        points: [
          "Biznes-tahlil va jarayon xaritasi",
          "UI/UX dizayn",
          "Veb-ilova yoki mobil ilova (iOS + Android)",
          "Backend, API va admin panel",
          "Integratsiyalar (Telegram, CRM, to'lov)",
          "4 hafta qo'llab-quvvatlash",
        ],
        stack: ["React", "Node.js", "Flutter", "Swift", "Kotlin", "Laravel", "Docker", "AWS"],
        accent: "ship",
        packages: [
          {
            name: "STANDARD",
            price: "$5,000 dan",
            term: "2 – 3 oy",
            desc: "Bitta aniq vazifani hal qiluvchi MVP: landing + forma, kichik mobil ilova yoki ichki veb-panel. Tezkor bozorga chiqish uchun.",
          },
          {
            name: "ADVANCED",
            price: "$15K – $40K",
            term: "4 – 6 oy",
            desc: "Murakkab biznes mantig'iga ega to'liq veb yoki mobil ilova — CRM integratsiya, push-bildirishnomalar, admin panel va API.",
            popular: true,
          },
          {
            name: "MEGA",
            price: "$50,000+",
            term: "6 – 12 oy",
            desc: "Yirik ekotizimlar: bir nechta ilova (veb + mobil + admin), mikroxizmatlar arxitekturasi, yuqori yuklama va bulutli infratuzilma.",
          },
        ],
      },
      {
        no: "02",
        icon: "consulting",
        tag: "Odoo ERP & AI Implementation",
        title: "Odoo ERP & AI Joriy qilish",
        subtitle: "Tarqoq jarayonlarni yagona tizimga birlashtirish va AI bilan kuchaytirish",
        geoSlug: "crm-erp-toshkent",
        detailsLabel: "{name} haqida batafsil →",
        body:
          "Korxonadagi alohida ishlayotgan bo'limlar, Excel jadvallar va qo'lda bajariladigan jarayonlarni yagona markazlashgan raqamli tizimga birlashtiramiz. Ustiga AI avtomatlashtirish qo'shib, takrorlanuvchi mexanik ishlardan jamoangizni butunlay xalos qilamiz.",
        points: [
          "Biznes-jarayon tahlili va xarita",
          "Odoo modullarini sozlash yoki custom ERP",
          "Ma'lumotlar migratsiyasi",
          "AI / chatbot integratsiya",
          "Xodimlarni o'qitish",
          "Qo'llab-quvvatlash va kuzatish",
        ],
        stack: ["Odoo ERP", "AI Automation", "Predictive Analytics", "Cloud"],
        accent: "develop",
        packages: [
          {
            name: "STANDARD",
            price: "$8,800 dan",
            term: "2 – 3 oy",
            desc: "Odoo standart modullarini bazaviy sozlash, ma'lumotlar ko'chirish va xodimlarni o'qitish. Kichik va o'rta biznes uchun dastlabki qadam.",
          },
          {
            name: "ADVANCED",
            price: "$25K – $35K",
            term: "4 – 6 oy",
            desc: "Biznes talablariga moslashtirilgan Odoo modullari, aqlli chat-botlar, hujjat aylanishi va jarayonlarni avtomatlashtirish.",
            popular: true,
          },
          {
            name: "MEGA",
            price: "$85,000+",
            term: "1 yil",
            desc: "Yirik korxona uchun to'liq raqamli transformatsiya: Odoo ERP barcha bo'limlarga, predictive analytics va chuqur AI integratsiyasi.",
          },
        ],
      },
    ],
  },
  portfolio: {
    eyebrow: "Portfolio",
    title: "So'nggi ishlarimiz.",
    subtitle: "Real, ishga tushirilgan loyihalar — har biri yechilgan muammo.",
    desktopLabel: "Desktop",
    mobileLabel: "Mobil",
    resultLabel: "Natija",
    liveLabel: "Batafsil",
    ctaTitle: "Keyingisi — sizniki",
    ctaBody: "Bo'sh joy sizning loyihangiz uchun. G'oyani birga tayyor mahsulotga aylantiramiz.",
    ctaButton: "Loyihangizni boshlaymiz",
    cases: [
      { segment: "Avtomobil sektori · CRM", title: "Motor Lux — CRM va savdo boshqaruvi", result: "Savdo va mijozlar bitta tizimda", tags: ["CRM", "Web"], desktopImg: "/cases/case-autoservice-desktop.webp", mobileImg: "/cases/case-autoservice-mobile.webp", url: "motorlux.uz", accent: "develop" },
      { segment: "Tibbiyot · CRM (PWA)", title: "MedFlow — klinika CRM va bemor qabuli", result: "Qabul boshqaruvi 3× tezlashdi", tags: ["PWA", "CRM"], desktopImg: "/cases/case-medflow-desktop.webp", mobileImg: "/cases/case-medflow-mobile.webp", url: "medflow.uz", accent: "preview" },
      { segment: "To'qimachilik · ERP (PWA)", title: "Grand Osiyo Textile — ERP va ombor tizimi", result: "Ombor real vaqtda boshqariladi", tags: ["ERP", "Ombor"], desktopImg: "/cases/case-textile-desktop.webp", mobileImg: "/cases/case-textile-mobile.webp", url: "grandosiyo.uz", accent: "ship" },
      { segment: "Ijara · Katalog", title: "Texnika Ijara — ijara va katalog sayti", result: "Onlayn bronlar 3× oshdi", tags: ["Web", "Katalog"], desktopImg: "/cases/case-texnika-desktop.webp", mobileImg: "/cases/case-texnika-mobile.webp", url: "texnika-ijara.uz", accent: "develop" },
      { segment: "Elektronika · E-commerce", title: "GadgetSpace — onlayn elektronika do'koni", result: "Konversiya 2.1× oshdi", tags: ["E-commerce"], desktopImg: "/cases/case-gadgetspace-desktop.webp", mobileImg: "/cases/case-gadgetspace-mobile.webp", url: "gadgetspace.uz", accent: "ship" },
      { segment: "Moda brendi · E-commerce", title: "X Wear — kiyim brendi uchun do'kon", result: "O'rtacha chek 28% oshdi", tags: ["E-commerce", "Web"], desktopImg: "/cases/case-xwear-desktop.webp", mobileImg: "/cases/case-xwear-mobile.webp", url: "xwear.uz", accent: "preview" },
      { segment: "Savdo · POS", title: "Hilol Market — savdo avtomatlashtirish", result: "Hisob-kitob 2× tezlashdi", tags: ["Retail", "POS"], desktopImg: "/cases/case-kassa-desktop.webp", mobileImg: "/cases/case-kassa-mobile.webp", url: "hilolmarket.uz", accent: "develop" },
    ],
  },
  features: {
    eyebrow: "Chuqurroq",
    resultLabel: "Natija",
    blocks: [
      { kicker: "Odoo ERP & AI", title: "Barcha operatsiyalar — bitta tizimda", body: "Savdo, ombor, buxgalteriya va HR alohida jadvallarda tarqoq edi. Biz Odoo ERP va AI agentlarini joriy qildik — jarayonlar bir panelda va avtomatlashgan.", result: "Ichki jarayonlar to'liq raqamli", frame: "browser", accent: "develop" },
      { kicker: "Mobil ilova", title: "Mijoz cho'ntagida bo'lgan biznes — kuchli biznes", body: "Segment uchun mobil ilova qurdik — buyurtma, to'lov, bildirishnoma hammasi bir joyda. Mijoz endi har kuni biznesingiz bilan cho'ntagida birga.", result: "Takroriy buyurtmalar 2× oshdi", frame: "phone", accent: "preview" },
      { kicker: "Maxsus dasturiy ta'minot", title: "Qo'lda qilinadigan ish — yashirin xarajat", body: "Adminlar kuniga soatlab bir xil ishni takrorlardi. Biz uni maxsus tizim va integratsiyalarga topshirdik. Endi tizim 24/7 ishlaydi, xato qilmaydi.", result: "Qo'l mehnati 70% qisqardi", frame: "browser", accent: "ship" },
    ],
  },
  founder: {
    eyebrow: "Aloqa",
    title: "Empire Group",
    name: "Empire Group",
    role: "AI & Custom App Development · Toshkent",
    bio: [
      "Biz g'oyadan tayyor mahsulotgacha bo'lgan yo'lni qisqartiramiz — ERP, AI, Web va App yechimlari bilan.",
      "Har bir loyihada bitta narsa muhim — natija: ishlaydigan, biznesni oldinga suradigan tizim.",
    ],
    photo: "/founder.webp",
    quote: "Biz kod yozmaymiz — biznesingizning muammosini hal qilamiz.",
    socials: [
      { label: "Telegram", value: "@muslimansoriy", href: "https://t.me/muslimansoriy" },
      { label: "Telefon", value: "+998 99 116 46 58", href: "tel:+998991164658" },
      { label: "Email", value: "muslimansoriy7@gmail.com", href: "mailto:muslimansoriy7@gmail.com" },
    ],
  },
  process: {
    eyebrow: "Qanday ishlaymiz",
    title: "Explore → Plan → Build → Commit",
    ctaLabel: "Loyihani boshlash",
    ctaHref: "#aloqa",
    steps: [
      { no: "01", title: "Explore", body: "G'oyani va muammoni tushunib olamiz. Biznesingiz, maqsadlaringiz va muammoli nuqtalarni chuqur o'rganamiz. Yechim yo'nalishini birga belgilaymiz.", tags: ["Tahlil", "Audit"] },
      { no: "02", title: "Plan", body: "Rejalashtirish va PRD yozish. Texnik zadaniya (TZ), arxitektura, dizayn — barchasi hujjatlashtiriladi. Muddat va byudjet aniq bo'ladi.", tags: ["PRD", "TZ", "Dizayn"] },
      { no: "03", title: "Build", body: "Ishlab chiqamiz — kod, test va integratsiya. Sprintlar bilan ishlaymiz, har bosqichda demo ko'rsatamiz. Siz jarayonni real vaqtda kuzatasiz.", tags: ["Dev", "Test", "Demo"] },
      { no: "04", title: "Commit", body: "Ishga tushirish va uzoq muddatli qo'llab-quvvatlash. Ishga tushiramiz, o'qitamiz va uzoq muddatli texnik yordam beramiz.", tags: ["Deploy", "Support"] },
    ],
  },
  whyUs: {
    eyebrow: "Nega Empire Group",
    title: "Ishonchli hamkor — boshidan oxirigacha.",
    items: [
      { title: "Fixed-scope narx", body: "Kelishilgan narx — yashirin xarajatlarsiz. Nimaga pul to'layotganingizni aniq bilasiz." },
      { title: "Senior muhandislar", body: "Tajribali jamoa: real ishga tushirilgan tizimlar tajribasi bilan." },
      { title: "Shaffof muddat", body: "Har sprint natijasi ko'rinadi, jarayonni real vaqtda kuzatasiz." },
      { title: "To'liq egalik", body: "Kod, dizayn va ma'lumotlar — hammasi sizniki. Hech qanday vendor lock-in yo'q." },
      { title: "Keyingi yordam", body: "Ishga tushirgandan keyin ham qo'llab-quvvatlash va rivojlantirish." },
      { title: "Zamonaviy stack", body: "Flutter, React, Next.js, Odoo, AI — zamonaviy va barqaror texnologiyalar." },
    ],
  },
  testimonials: {
    eyebrow: "Mijozlar fikri",
    title: "Mijozlarimiz nima deydi.",
    items: [
      { quote: "Empire Group bizning eski qog'ozdagi ishimizni to'liq tizimga o'tkazishdi. Endi barcha buyurtmalarni bitta joydan boshqaramiz — vaqt ancha tejaldi.", name: "Aliya M.", role: "CRM loyihasi · Motor Lux" },
      { quote: "Empire bilan ishlash oson bo'ldi. Muddat va byudjet aniq edi, hech qanday kutilmagan masalalar chiqmadi.", name: "Jasur T.", role: "E-commerce · GadgetSpace" },
      { quote: "Empire klinika ishini AI qo'shib avtomatlashtirdi. Bemor navbati muammosi hal bo'ldi, qabul ancha tartibli.", name: "Doniyor R.", role: "MedFlow · klinika" },
      { quote: "Zamonaviy dizayn va tez ishlaydigan sayt. Savdo hajmi ko'tarildi, mijozlar fikri ijobiy.", name: "Laziza K.", role: "X Wear · e-commerce" },
    ],
    proofTitle: "Telegram orqali — jonli isbot",
    proofNote: "Mijozlar bilan haqiqiy yozishmalar",
  },
  credentials: {
    eyebrow: "Ishonch va tasdiq",
    title: "Rasmiy maqom va sertifikatlar.",
    subtitle:
      "Har bir hamkorlik va maqom rasmiy hujjat bilan tasdiqlangan. Ro'yxat yangi sertifikatlar bilan to'ldirib boriladi.",
    activeLabel: "Tasdiqlangan",
    pendingLabel: "Kutilmoqda",
    placeholderTitle: "Sertifikat",
    placeholderNote: "Jarayondagi keyingi sertifikat uchun joy.",
    viewLabel: "Ko'rish uchun bosing",
    closeLabel: "Yopish",
    prevLabel: "Oldingi",
    nextLabel: "Keyingi",
    items: [
      {
        name: "Odoo Learning Partner",
        image: "/sertifikat/odoo-learning-partner.svg",
        issuer: "Odoo S.A.",
        note: "Odoo ERP joriy qilish bo'yicha rasmiy hamkorlik maqomi.",
        status: "active",
      },
      {
        name: "Davlat ro'yxatidan o'tganlik guvohnomasi",
        issuer: "Toshkent sh., Mirzo Ulug'bek tumani DXM",
        note: "\"EMPIRE GROUP CORP\" MCHJ — 2025-yil 16-iyuldan davlat reyestrida.",
        status: "active",
      },
      {
        name: "IT Park rezidenti",
        issuer: "IT Park O'zbekiston",
        note: "Rezidentlik arizasi ko'rib chiqilmoqda.",
        status: "pending",
      },
    ],
  },
  faq: {
    eyebrow: "Savol-javob",
    title: "Ko'p so'raladigan savollar.",
    items: [
      { q: "Loyiha qancha vaqt oladi?", a: "Kichik MVP 3–4 hafta, o'rtacha loyiha 2–3 oy, yirik korporativ tizim 4–6 oy. Aniq muddat Explore bosqichida belgilanadi." },
      { q: "Narx qanday hisoblanadi?", a: "Fixed-scope: loyiha hajmi aniqlangach, aniq narx beriladi. Yashirin xarajatlar yo'q. Paketlar $5,000 dan boshlanadi." },
      { q: "Narxlar nega farq qiladi?", a: "Narx murakkablik, integratsiyalar va muddatga bog'liq. Har loyiha uchun alohida hisoblab beramiz." },
      { q: "Ishlab bo'lingandan keyin yordam beramizmi?", a: "Ha, ishga tushirgandan keyin qo'llab-quvvatlash, xatolarni tuzatish va rivojlantirish davom etadi." },
      { q: "To'lov qanday amalga oshiriladi?", a: "Bosqichma-bosqich: oldindan qism, keyin sprint natijalariga qarab. To'lov usullari kelishiladi." },
      { q: "Kod va ma'lumot kimga tegishli bo'ladi?", a: "Barchasi sizga tegishli. To'liq egalik sizda — hech qanday vendor lock-in yo'q." },
      { q: "Mavjud tizimimni davom ettira olasizmi?", a: "Ha, mavjud loyiha yoki tizimni ko'rib chiqib, davom ettirish yoki qayta qurish bo'yicha yechim beramiz." },
      { q: "Konsultatsiya bepulmi?", a: "Ha. Explore bosqichida barcha savollarga javob beramiz va aniq reja tuzamiz — hech qanday majburiyat yo'q." },
    ],
  },
  cta: {
    eyebrow: "Bepul konsultatsiya",
    title: "Bepul konsultatsiya oling — keyin qaror qilasiz.",
    subtitle: "Formani to'ldiring, biz siz bilan bog'lanamiz. G'oyani, byudjetni va muddatni birga muhokama qilamiz. Hech qanday majburiyat yo'q — avval suhbat.",
    button: { label: "Bepul konsultatsiya", href: "https://t.me/muslimansoriy" },
    formTitle: "Bepul konsultatsiya",
    formSubtitle: "Ma'lumotlaringizni qoldiring — tez orada bog'lanamiz.",
  },
  footer: {
    tagline:
      "Biznes uchun AI va custom ilova ishlab chiqish — mobil, veb, maxsus dasturiy ta'minot va Odoo ERP & AI joriy etish. G'oyadan ishga tushgunga qadar.",
    columns: [
      { title: "Xizmatlar", links: [
        { label: "Maxsus dasturiy ta'minot", href: "#xizmatlar" },
        { label: "Odoo ERP & AI Joriy qilish", href: "#xizmatlar" },
      ]},
      { title: "Kompaniya", links: [
        { label: "Loyihalar", href: "#loyihalar" },
        { label: "Jarayon", href: "#jarayon" },
        { label: "Mijozlar fikri", href: "#sharhlar" },
        { label: "Savollar", href: "#savollar" },
        { label: "Blog", href: "/blog" },
      ]},
      { title: "Aloqa", links: [
        { label: "muslimansoriy7@gmail.com", href: "mailto:muslimansoriy7@gmail.com" },
        { label: "+998 99 116 46 58", href: "tel:+998991164658" },
        { label: "Telegram", href: "https://t.me/muslimansoriy" },
        { label: "Instagram", href: "https://instagram.com/empiregroup.uz" },
      ]},
    ],
    copyright: "© 2026 Empire Group. Barcha huquqlar himoyalangan.",
    legal: "Maxfiylik siyosati · Foydalanish shartlari",
  },
};
