export const GEO_ENTRIES = {
  'veb-sayt-yaratish-toshkent': {
    slug: 'veb-sayt-yaratish-toshkent',
    city: 'toshkent',
    serviceType: 'web',
    title: "Toshkentda Veb-sayt va Web App Yaratish — Empire Group",
    description: "Toshkent korxonalari uchun yuqori tezlikdagi veb-saytlar va biznes ilovalar. $5,000 dan. 2-4 oyda tayyor.",
    h1: "Toshkentda Biznes uchun Veb-sayt Yaratish",
    intro: "Toshkent — O'zbekiston biznes markazi. 800,000+ ro'yxatdan o'tgan korxona shu shaharda faoliyat yuritadi. Raqobat kuchli, onlayn borish — zarurat. Biz Toshkent kompaniyalari uchun faqat chiroyli emas, balki sotuvga yo'naltirilgan veb-saytlar yaratamiz.",
    localStats: "Toshkent bo'yicha 40+ B2B loyiha amalga oshirganmiz. O'rtacha mijoz konversiyasi veb-sayt joriy etilgandan 3 oy ichida 2.4x oshgan.",
    caseStudy: "Motor Lux — Toshkentdagi avtoservis. Oldingi saytda oyiga 5-6 ta online buyurtma kelardi. Biz CRM + sayt integratsiyasi qildik: buyurtma formasi → avtomatik Telegram xabar → admin panel. Natija: 3 oyda online buyurtmalar 5x ga oshdi, 47 ta yangi doimiy mijoz qo'shildi.",
    services: ['Korporativ veb-saytlar', 'E-commerce do\'konlar', 'Landing page + CRM', 'PWA ilovalar'],
    price: "$5,000 dan boshlanadi",
  },
  'mobil-ilova-yaratish-toshkent': {
    slug: 'mobil-ilova-yaratish-toshkent',
    city: 'toshkent',
    serviceType: 'mobile',
    title: "Toshkentda Mobil Ilova Yaratish — iOS va Android | Empire Group",
    description: "Toshkent biznes uchun iOS va Android mobil ilovalar: React Native va Flutter. $7,500 dan. MVP 2-3 oyda.",
    h1: "Toshkentda Mobil Ilova Ishlab Chiqish",
    intro: "O'zbekistonda smartfon foydalanuvchilari 22 mln dan oshdi. Toshkent aholisining 89% mobil internetdan foydalanadi. Biznesingiz mobil bo'lmasa — mijozlarning katta qismini yo'qotasiz. Biz cross-platform (iOS + Android) ilovalar yaratamiz — bitta kodda, ikki platformada.",
    localStats: "10+ mobil ilova loyihasi ishga tushirilgan. O'rtacha App Store reytingi: 4.7 yulduz. Eng tez MVP: 7 hafta.",
    caseStudy: "Hilol Market — Toshkentdagi do'konlar tarmog'i. Kassirlar uchun PWA kassa ilovasi yaratdik: kundalik savdo, xarajat kiritish, smena yopish va hisobot. Natija: har bir do'konda kunlik hisobot vaqti 40 min dan 5 min ga tushdi.",
    services: ['iOS va Android ilovalar', 'React Native / Flutter', 'PWA ilovalar', 'Backend + API integratsiya'],
    price: "$7,500 dan boshlanadi",
  },
  'crm-erp-toshkent': {
    slug: 'crm-erp-toshkent',
    city: 'toshkent',
    serviceType: 'crm',
    title: "Toshkentda CRM va ERP Joriy Etish — Odoo, Custom | Empire Group",
    description: "Toshkent korxonalari uchun CRM va ERP tizimlar: Odoo joriy etish yoki custom ishlab chiqish. $5,000 dan.",
    h1: "Toshkentda CRM va ERP Tizimlar",
    intro: "Toshkent kompaniyalarining 70% hali Excel va qo'lda hisobot yuritadi. Bu xatolar, yo'qolgan mijozlar va nazorat yo'qligi demak. CRM joriy etsangiz — har bir mijoz, har bir bitim nazorat ostida bo'ladi. Biz Odoo ERP joriy etamiz yoki biznesingizga mos custom CRM yaratamiz.",
    localStats: "15+ CRM/ERP loyiha: to'qimachilik, tibbiyot, avtoservis, ta'lim sohalari. O'rtacha ROI: 6 oyda investitsiya qaytadi.",
    caseStudy: "Grand Osiyo Textile — Toshkentdagi to'qimachilik fabrikasi. 5 bosqichli ishlab chiqarish (mato → bo'yoq → tikuv → paketlash → eksport) nazorati uchun custom ERP yaratdik. Natija: ombor yo'qotishlari 23% ga kamaydi, buyurtma kuzatish vaqti 3 kundan 4 soatga tushdi.",
    services: ['Odoo ERP joriy etish', 'Custom CRM ishlab chiqish', 'Biznes jarayonlarni avtomatlashtirish', 'Ma\'lumotlar migratsiyasi'],
    price: "$5,000 dan boshlanadi",
  },
  'veb-sayt-yaratish-samarqand': {
    slug: 'veb-sayt-yaratish-samarqand',
    city: 'samarqand',
    serviceType: 'web',
    title: "Samarqandda Veb-sayt Yaratish — Empire Group",
    description: "Samarqand biznes uchun veb-saytlar: turizm, ishlab chiqarish, savdo. Mahalliy tajriba bilan. $5,000 dan.",
    h1: "Samarqandda Biznes uchun Veb-sayt",
    intro: "Samarqand — O'zbekistonning 2-yirik iqtisodiy markazi, yiliga 3 mln+ turist. Turizm, qishloq xo'jaligi va sanoat bu yerda jadal rivojlanmoqda. Samarqand biznesi uchun sayt — nafaqat vizitka, balki online savdo kanali.",
    localStats: "Samarqand hududi bo'yicha 8 ta loyiha: turizm agentliklari, ishlab chiqarish korxonalari va savdo kompaniyalari.",
    caseStudy: "Samarqand turizm agentligi uchun ko'p tilli sayt (uz/ru/en) + online bron tizimi yaratdik. 6 oy ichida online bronlar 340% ga oshdi, Google'da \"Samarkand tour\" so'zi bo'yicha 1-sahifaga chiqdik.",
    services: ['Turizm saytlari', 'Ishlab chiqarish korxonalari uchun', 'Savdo va eksport kompaniyalari', 'Ko\'p tilli saytlar'],
    price: "$5,000 dan boshlanadi",
  },
  'it-xizmatlar-buxoro': {
    slug: 'it-xizmatlar-buxoro',
    city: 'buxoro',
    serviceType: 'web',
    title: "Buxoroda IT Xizmatlar — Veb-sayt va Dasturiy Ta'minot | Empire Group",
    description: "Buxoro korxonalari uchun veb-sayt, mobil ilova va CRM ishlab chiqish. Masofaviy hamkorlik. $5,000 dan.",
    h1: "Buxoroda IT Xizmatlar va Dasturiy Ta'minot",
    intro: "Buxoro viloyatida 45,000+ kichik va o'rta biznes ro'yxatga olingan. Ko'pchiligi onlayn imkoniyatlardan hali foydalanmaydi. Biz masofaviy ishlaymiz — Buxorodagi mijozlar bilan Zoom orqali uchrashib, loyihani boshdan oxirigacha Toshkentdek sifatda amalga oshiramiz.",
    localStats: "Buxoro viloyatidan 5 ta loyiha: hunarmandchilik eksport, mehmonxona bron, mahalliy marketplace.",
    caseStudy: "Buxoro hunarmandchilik eksport kompaniyasi uchun 3 tilli katalog sayt + WhatsApp integratsiya yaratdik. Xalqaro buyurtmalar 2x ga oshdi — asosan Turkiya va Xitoydan.",
    services: ['Korporativ saytlar', 'Online katalog va do\'konlar', 'Bron tizimlari', 'CRM va hisobotlar'],
    price: "$5,000 dan boshlanadi",
  },
};

export const geoSlugs = Object.keys(GEO_ENTRIES);

export function getGeoEntry(slug) {
  return GEO_ENTRIES[slug] || null;
}
